FROM golang:1.21-alpine

RUN apk add --no-cache gcc musl-dev sqlite-dev ffmpeg

WORKDIR /app

# Install air for hot reload
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]